spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/development

#          jwk-set-uri: http://keycloak:8080/realms/development/protocol/openid-connect/certs
#      client:
#        registration:
#          keycloak:
#            client-id: iraise-dev
#            client-secret: GcE1IPmJ2YnVlzMBxwS2ygQuHYvbvmvj
#            scope: openid
#            authorization-grant-type: authorization_code
#            client-name: Keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://keycloak:8080/realms/development
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8085/realms/development
#          jwk-set-uri: http://localhost:8085/realms/development/protocol/openid-connect/certs
#      client:
#        registration:
#          keycloak:
#            client-id: iraise-dev
#            client-secret: GcE1IPmJ2YnVlzMBxwS2ygQuHYvbvmvj
#            scope: openid
#            authorization-grant-type: authorization_code
#            client-name: Keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8085/realms/development

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8765
  max-http-request-header-size: 10KB
logging:
  level:
    org.springframework.security: debug