spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/development
          jwk-set-uri: http://localhost:8085/realms/development/protocol/openid-connect/certs


server:
  port: 8765
